branch-defaults:
  main:
    environment: Goatsportalne-env
  nini-version1:
    environment: Goatsportalne-env
environment-defaults:
  Goatsportalne-env:
    branch: null
    repository: null
global:
  application_name: GOATS Portal NE
  default_ec2_keyname: null
  default_platform: Node.js 16 running on 64bit Amazon Linux 2
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: git
  workspace_type: Application
