import { createSlice } from '@reduxjs/toolkit';

// fake data to use prior to DB
const mockOrder = [
  {
    id: '1234',
    referenceNumber: '1234',
    invoiceNumber: '5678',
    status: 'PLACED',
    datePlaced: '2/24/2022',
    revenue: 26.00,
    isSelfOrder: false,
    isGift: true,
    giftFor: 'Mr. Gompei',
    giftMessage: 'Enjoy this cheese made from other goats! On second thought, maybe not...',
    shipmentTrackingNumber: 'ABCD',
    customer: {
      id: '1',
      email: 'customer@wpi.edu',
      firstName: 'Frank',
      lastName: 'McGovern',
      phoneNumber: '20397588636',
  
    },
    productsOrdered: [{
      id: '1',
      quantity: 3,
      product: {
        id: 'jPL6',
        name: 'plain',
        productDescription: 'A six oz log of plain goat cheese',
      }	
    }],
    shippingAddress: {
      id: '1',
      streetAddress: '86 Brook road',
      city: 'Southwick',
      state: 'NH',
      zipCode: '00675',
    },
    invoice: {
      id: '1',
      invoiceNumber: '5678',
      expense: 21.50,
      isPaid: true,
    },
  },
  {
    id: '1235',
    referenceNumber: '1235',
    invoiceNumber: '5678',
    status: 'PROCESSED',
    datePlaced: '2/24/2022',
    revenue: 26.00,
    isSelfOrder: false,
    isGift: true,
    giftFor: 'Mr. Gompei',
    giftMessage: 'Enjoy this cheese made from other goats! On second thought, maybe not...',
    shipmentTrackingNumber: 'ABCD',
    customer: {
      id: '1',
      email: 'customer@wpi.edu',
      firstName: 'Chad',
      lastName: 'Buttler',
      phoneNumber: '20397588636',
  
    },
    productsOrdered: [{
      id: '1',
      quantity: 3,
      product: {
        id: 'jPL6',
        name: 'plain',
        productDescription: 'A six oz log of plain goat cheese',
      }	
    }],
    shippingAddress: {
      id: '1',
      streetAddress: '86 Brook road',
      city: 'Southwick',
      state: 'NH',
      zipCode: '00675',
    },
    invoice: {
      id: '1',
      invoiceNumber: '5678',
      expense: 21.50,
      isPaid: false,
    },
  },
  {
    id: '1236',
    referenceNumber: '1236',
    invoiceNumber: '5678',
    status: 'PROCESSED',
    datePlaced: '2/24/2022',
    revenue: 26.00,
    isSelfOrder: false,
    isGift: true,
    giftFor: 'Mr. Gompei',
    giftMessage: 'Enjoy this cheese made from other goats! On second thought, maybe not...',
    shipmentTrackingNumber: 'ABCD',
    customer: {
      id: '1',
      email: 'customer@wpi.edu',
      firstName: 'William',
      lastName: 'Fancyson',
      phoneNumber: '20397588636',
  
    },
    productsOrdered: [{
      id: '1',
      quantity: 3,
      product: {
        id: 'jPL6',
        name: 'plain',
        productDescription: 'A six oz log of plain goat cheese',
      }	
    }],
    shippingAddress: {
      id: '1',
      streetAddress: '86 Brook road',
      city: 'Southwick',
      state: 'NH',
      zipCode: '00675',
    },
    invoice: {
      id: '1',
      invoiceNumber: '5678',
      expense: 21.50,
      isPaid: false,
    },
  },
  {
    id: '1237',
    referenceNumber: '1237',
    invoiceNumber: '5678',
    status: 'PROCESSED',
    datePlaced: '2/24/2022',
    revenue: 26.00,
    isSelfOrder: false,
    isGift: true,
    giftFor: 'Mr. Gompei',
    giftMessage: 'Enjoy this cheese made from other goats! On second thought, maybe not...',
    shipmentTrackingNumber: 'ABCD',
    customer: {
      id: '1',
      email: 'customer@wpi.edu',
      firstName: 'James',
      lastName: 'Fazzino',
      phoneNumber: '20397588636',
  
    },
    productsOrdered: [{
      id: '1',
      quantity: 3,
      product: {
        id: 'jPL6',
        name: 'plain',
        productDescription: 'A six oz log of plain goat cheese',
      }	
    }],
    shippingAddress: {
      id: '1',
      streetAddress: '86 Brook road',
      city: 'Southwick',
      state: 'NH',
      zipCode: '00675',
    },
    invoice: {
      id: '1',
      invoiceNumber: '5678',
      expense: 21.50,
      isPaid: false,
    },
  }];


export const orderSlice = createSlice({
  name: 'order',
  initialState: mockOrder,
  reducers: {
    deleteOrder: (state) => {
    },
    addOrder: (state, action) => {
    },
    editOrder: (state, action) => {
    },
    selectOrder: (state) => {
        return state
    }
  },
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: (builder) => {
    
  },
});

export const {deleteOrder, addOrder, editOrder, selectOrder} = orderSlice.actions;

export default orderSlice.reducer;